apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    # Force DNS refresh for monitoring namespace
    monitoring.svc.cluster.local:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 5
        }
        cache 5
        loop
        reload
        loadbalance
    }
