apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- prometheus-rbac.yaml
- prometheus-config.yaml
- grafana-provisioning.yaml
- prometheus.yaml
- node-exporter.yaml
- alloy.yaml
- grafana.yaml
- loki-config.yaml
- loki.yaml
- kube-state-metrics.yaml
configMapGenerator:
- name: alloy-config
  namespace: monitoring
  files:
  - config.alloy=alloy-config.alloy
