apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Raspberry Pi Node Exporter (provides real hardware metrics via hostNetwork)
      - job_name: 'raspberry-pi'
        static_configs:
          - targets: ['node-exporter:9100']
        scrape_interval: 10s
        metrics_path: /metrics
        
      # Kubernetes Pod Discovery
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
